package com.github.goldy1992.mp3player.commons

object MetaDataKeys {
    const val META_DATA_KEY_FILE_NAME = "META_DATA_KEY_FILE_NAME"
    const val META_DATA_DIRECTORY = "META_DATA_DIRECTORY"
    const val META_DATA_PARENT_DIRECTORY_NAME = "META_DATA_PARENT_DIRECTORY_NAME"
    const val META_DATA_PARENT_DIRECTORY_PATH = "META_DATA_PARENT_DIRECTORY_PATH"
}