plugins: ['@semantic-release/commit-analyzer',
          '@semantic-release/release-notes-generator',
          '@semantic-release/github',
          [ "@semantic-release/git", {
            "assets": [ "dist/**/*.{js,css}", "docs", "package.json" ],
            "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
          } ]
          '@semantic-release/exec']
branch: master
ci: false
dryRun: true
debug: true