name: master-build-release
on:
  push:
    branches:
      - master
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


# code to create sources.zip and checksum to upload as github release asset.
# sudo apt install zip
# sudo zip -r sources.zip Mp3Player/q -x Mp3Player/google-services.json
# md5sum my-src.zip > md5-checksum.txt