name: Pull Request to master Workflow
run-name: Pull Request to master Workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master
jobs:
  run-unit-tests:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: Build all Debug flavors
        run: ./gradlew assemble -x app:packageFullRelease -x app:signFullReleaseBundle -x app:validateSigningFullRelease testFullDebugUnitTest testDebugUnitTest

      - name: Gradle and create coverage report
        run: ./gradlew jacocoTestReport

      - name: Run Lint
        run: ./gradlew lint