name: Push to master Workflow
run-name: Push to master
on:
  push:
    branches:
      - master

jobs:
  run-ui-tests:
    name: Test
    uses: ./.github/workflows/ui-tests-workflow.yml
    secrets:
      RELEASE_SERVICE_ACCOUNT_JSON: ${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  semantic-release:
    name: Semantic Release
    needs: [ run-ui-tests ]
    uses: ./.github/workflows/semantic-release-workflow.yml
    secrets:
      SEMANTIC_RELEASE_FINE_GRAINED_TOKEN: ${{ secrets.SEMANTIC_RELEASE_FINE_GRAINED_TOKEN }}
      KEY_STORE_BASE64: ${{ secrets.KEY_STORE_BASE64 }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      RELEASE_SERVICE_ACCOUNT_JSON: ${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}